loadsmart:
  target: dev
  outputs:
    dev:
      type: postgres
      host: loadsmart.ccsxmttth1av.us-east-1.rds.amazonaws.com
      user: 
      password: 
      port: 
      dbname: 
      schema: 

